name: 'SquareCloud Action'
description: 'Deploy your application to square cloud using Github Actions'
author: 'richaardev'
branding:
  icon: square
  color: black

inputs:
  excludes:
    required: false
    description: 'excludes some files'
    default: '.git'
  token:
    required: true
    description: 'square cloud api token'
    default: null
  application_id:
    required: true
    description: 'square cloud application id'
    default: null
  restart:
    required: false
    description: 'restart aplication after upload'
    default: false
runs:
  using: 'node16'
  main: 'dist/index.js'
